const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const read = (...parts) => fs.readFileSync(path.join(ROOT, ...parts), 'utf8').trimEnd();
const write = (target, content) => {
  const full = path.join(ROOT, target);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content.replace(/\r\n/g, '\n').trimEnd() + '\n');
};

const header = read('src', 'header-sibylla.txt');
const css = read('src', 'sibylla.css');

write('build/sibylla.css', [
  '/* Sibylla Midnight build — generated by scripts/build.js */',
  '',
  css,
].join('\n'));

write('themes/sibylla.theme.css', [header, '', css].join('\n'));

console.log('Built build/sibylla.css');
console.log('Built themes/sibylla.theme.css');
console.log('No flavor file is generated in V3.');
