const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const read = (...parts) => fs.readFileSync(path.join(ROOT, ...parts), 'utf8').trimEnd();
const write = (target, content) => {
  const full = path.join(ROOT, target);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content.replace(/\r\n/g, '\n').trimEnd() + '\n');
};

const header = read('src', 'header-sibylla.txt');
const parts = [
  read('src', 'base', 'layout.css'),
  read('src', 'options', 'settings.css'),
  read('src', 'theme', 'sibylla.css'),
  read('src', 'fixes', 'compat.css'),
];

const build = [
  '/* Sibylla Midnight build — generated by scripts/build.js */',
  '/* Runtime dependencies: none from upstream GitHub. */',
  ...parts,
].join('\n\n');

write('build/sibylla.css', build);

const onlineImport = "@import url('https://raw.githubusercontent.com/ussmarines/DiscordTheme/main/build/sibylla.css');";
const theme = [header, '', onlineImport].join('\n');
write('themes/sibylla.theme.css', theme);
write('themes/flavors/sibylla.theme.css', theme.replace('@name Sibylla Midnight', '@name Sibylla Midnight (flavor)'));

console.log('Built build/sibylla.css');
console.log('Built themes/sibylla.theme.css');
console.log('Built themes/flavors/sibylla.theme.css');
